npm-install:
	npm install

#Si exiten problemas con las dependencias, se puede ejecutar el siguiente comando
npx-npm-check-updates:
	npx nmp-check -u

npm-i-formik:
	npm install formik

npm-i-yup:
	npm install yup

npm-i-dotenv:
	npm install dotenv